name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
      - 'Acknowledgments.md'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.github/workflows/publish.yml'

env:
  EM_VERSION: 3.1.26
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Emscripten cache
      id: cache-system-libraries
      uses: actions/cache@v3
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
        
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v12
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

    - name: Test
      run: |
          export EMSCRIPTEN_CMAKE_TOOLCHAIN=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          ./build.js
          ./test.js
